### PR TITLE
0 70 stable

### PR DESCRIPTION
**Pull request by patrickmcelwee**
I was installing Skrill in my 0.70.4 store and got an error because engine.rb was anticipating the Spree::BillingIntegration namespacing from Spree 1.0 in the 0-70-stable branch. The pull request just eliminates the namespacing in the 0-70 branch.

I also caught a couple small README errors.

BTW, I ran the tests and 4 of 6 failed, though they had nothing to do with these small changes. In case it's helpful, I put the output up in this Gist: https://gist.github.com/2001927

### CODE REVIEW

**Comment by DavidOliver** [comment]
Thanks @patrickmcelwee - this helped me get it installed in 0.70.4.

Couple of notes:

Your Gemfile line looks like it needs completion (branch part is incomplete).

Isn't it recommended to keep Gemfile.lock in version control?

**Comment by patrickmcelwee** [comment]
I cleaned up the pull request. I deleted an unnecessary commit modifying .gitignore and I fixed my own typo.

Yes, my original pull request was rather sloppy, I see. Thanks for pointing it out. Removing Gemfile.lock was meant to be only for me, but it got wrapped up in my pull request. (This was my first pull request.)

**Comment by DavidOliver** [comment]
I recently made my first pull request here at GitHub, too, and found that subsequent commits are included by default. I believe it's possible to adjust the range, though.

Thanks again.

**Comment by radar** [comment]
This is probably a bit too late, but we've fixed it now. Apologies for not fixing it earlier.

**Pull request closed without merging**
